### ISSUE TITLE
CurseForge 403 Forbidden

### ISSUE THREAD

**Issue by FinlayDaG33k** [packwiz/packwiz#116] opened 2022-05-16 17:55 UTC
Hii there,

I'm trying to install some mods to my pack from CF, however, they all throw the same error:
```
Finlay@Richthoven MINGW64 /f/repos/FinlayDaG33k/dpm-mc-modpack (main)
$ packwiz cf install https://www.curseforge.com/minecraft/mc-mods/dynamic-fps/files/3606973
failed to request addon ID 335493: 403 Forbidden

Finlay@Richthoven MINGW64 /f/repos/FinlayDaG33k/dpm-mc-modpack (main)
$ packwiz cf install https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap
failed to request addon ID 263420: 403 Forbidden
```

Is there some setup I need to do beforehand?

**Comment by comp500** [comment] 2022-05-16 18:29
Duplicate of #114; this is the same issue with a newer error message.

**Closed by comp500** 2022-05-16 18:29 UTC
