### ISSUE TITLE
Flag to fuzzy match Minecraft/loader versions

### ISSUE THREAD

**Issue by CodeF53** [packwiz/packwiz#111] opened 2022-05-03 20:52 UTC
Often you know certain mods support a minecraft version despite their Curse/Modrinth pages not being updated.

 it would be nice to do like 
`packwiz mr install mod force`

Packwiz then finds the closest matching version to your specified `[versions]`

**Comment by comp500** [comment] 2023-01-20 06:34
Duplicate of https://github.com/packwiz/packwiz/issues/31

**Closed by comp500** 2023-01-20 06:34 UTC
Labels: enhancement
