### ISSUE TITLE
packwiz considers newer version of mod on Modrinth to be "older" than an earlier version

### ISSUE THREAD

**Issue by copygirl** [packwiz/packwiz#149] opened 2022-08-19 06:08 UTC
When running `packwiz update --all`, it appears to not consider Create's [version `v0.5.0d`](https://modrinth.com/mod/create/version/1.18.2-0.5.0.d) to be newer than [version `v0.5.0c`](https://modrinth.com/mod/create/version/1.18.2-0.5.0c). It did not automatically update to this newer version, and after manually running `packwiz mr get https://modrinth.com/mod/create/version/xRw8XV1l`, it even wants to downgrade.

**Comment by copygirl** [comment] 2022-08-19 06:31
Same with its dependency, [flywheel](https://modrinth.com/mod/flywheel). I suppose this has something to do with them changing their version strings? Create added a dot between the SemVer and letter they use, and Flywheel switched around the Minecraft version and mod version in their version string.

**Comment by copygirl** [comment] 2022-08-19 06:54
Not sure if related, but packwiz also just downgraded [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries) (CurseForge) from 1.4.8 to 1.4.7? I can't reproduce it a second time, though. I'll have a closer look at what the update command does in the future.

**Comment by comp500** [comment] 2022-08-23 01:26
The semver comparison does consider `0.5.0.d` lower than `0.5.0c`, that's consistent with the semver standard... unfortunately quite a few mods aren't compliant with semver, it's not enforced by Modrinth - I might have to switch to just comparing by release timestamp.

Flywheel might be fixed now, they seem to have removed Minecraft versions from all the version fields. I can't reproduce the Supplementaries problem, it might be an issue with the CF API.

**Comment by copygirl** [comment] 2022-08-26 09:23
To be fair neither `0.5.0.d` nor `0.5.0c` are valid semver version numbers, so I'm unsure how you'd even begin to sort them. You can't have third dot in the version, and the major, minor and patch numbers can't just have random letters in them. Only `0.5.0-e` would be valid. (I might have written my own lenient SemVer parsing library once, so I know the pain.)

**Comment by comp500** [comment] 2022-08-26 14:24
The full version is `1.18.2-0.5.0.d` so the two versions are compared on the prerelease data, not version numbers themselves - under semver section `11.4.3` "Numeric identifiers always have lower precedence than non-numeric identifiers"; hence `0` < `0c`

**Comment by comp500** [comment] 2022-08-26 15:11
Yeah... I suggest you report this to the Create devs, unfortunately this kind of issue will keep cropping up. It would help a lot if Modrinth enforced a standard way of comparing versions - if I only compare by release timestamp as their update endpoint does, it would break version comparison when an author releases versions out-of-order. The version number field is essentially useless if it has no defined semantics; heuristics only go so far.

**Closed by comp500** 2022-08-26 15:11 UTC
