### ISSUE TITLE
[Bug] Support modrinth version urls without having to hand edit them

### ISSUE THREAD

**Issue by ChristopherHaws** [packwiz/packwiz#175] opened 2022-12-22 23:00 UTC
Any chance you could add support for modrinth using the version urls from modrinth without having to hand edit them?

Currently, I get an error when pasting in a modrinth version url:
```
> packwiz mr add https://modrinth.com/mod/fabric-api/version/0.69.0+1.19.2
Failed installing mod: failed to fetch version 0.69.0+1.19.2: invalid character 'I' looking for beginning of value
```

However if I hand edit the url to include the `version id` it works:
```
> packwiz mr add https://modrinth.com/mod/fabric-api/version/25Hm7c3j
Installing fabric-api-0.69.0+1.19.2.jar from version 0.69.0+1.19.2
```

**Comment by comp500** [comment] 2022-12-23 00:03
Duplicate of https://github.com/packwiz/packwiz/issues/103.

**Comment by comp500** [comment] 2022-12-23 00:03
Duplicate of https://github.com/packwiz/packwiz/issues/103

**Closed by comp500** 2022-12-23 00:03 UTC
