### ISSUE TITLE
GUIs are blank on Prism Launcher / Steam Deck in Game Mode

### ISSUE THREAD

**Issue by endigma** [packwiz/packwiz#271] opened 2023-12-30 01:31 UTC
The "optional mods" and other UIs are completely blank in the steam deck's game mode under Prism Launcher.

**Comment by comp500** [comment] 2023-12-30 03:53
Duplicate of https://github.com/packwiz/packwiz-installer/issues/33

**Closed** 2023-12-30 03:54 UTC
