### ISSUE TITLE
side indexed files

### ISSUE THREAD

**Issue by Commandcracker** [packwiz/packwiz#249] opened 2023-08-22 22:23 UTC
I have a Mod-pack that has folders like `config/defaultoptions`, `resourcepacks` or `shaderpacks` and files like `config/wecui3.yml` that are not needed by the server, but i cant set their side because they are indexed files. I would like to have some way to accomplish an side change :D.

**Comment by comp500** [comment] 2023-08-22 22:39
Duplicate of #82

**Closed by comp500** 2023-08-22 22:39 UTC
