### ISSUE TITLE
packwiz and multimc disabled mods

### ISSUE THREAD

**Issue by pinchese** [packwiz/packwiz#143] opened 2022-07-22 23:50 UTC
currently whenever people disable mods in the multimc instance, packwiz just redownloads the mods on launch

i think packwiz should see if the mod has been renamed to have ".disabled" at the end, so that it won't try to redownload the mod

**Comment by comp500** [comment] 2022-07-22 23:51
Duplicate of https://github.com/packwiz/packwiz-installer/issues/13

**Closed by comp500** 2022-07-22 23:51 UTC
