### ISSUE TITLE
Feature: Add noconfirm/yes option for install

### ISSUE THREAD

**Issue by furudbat** [packwiz/packwiz#109] opened 2022-04-21 10:14 UTC
For more automatic and non-interactive builds/packaging.

## Problem

`packwiz modrinth install dynamic-fps`:  
> Installing dynamic-fps-2.1.0.jar from version v2.1.0
> Finding dependencies...
> Dependencies found:
> Fabric API
> Would you like to install them? [Y/n]: 
> Dependency "Fabric API" successfully installed! (fabric-api-0.51.1+1.18.2.jar)

Skip the "Would you like to install them?"-Question (and answer with "Y").

## Example

```
packwiz modrinth install dynamic-fps -y
packwiz modrinth install dynamic-fps  --noconfirm
```

**Comment by comp500** [comment] 2022-04-21 16:40
Duplicate of https://github.com/packwiz/packwiz/issues/46

**Closed by comp500** 2022-04-21 16:40 UTC
