### ISSUE TITLE
[feature] github mod release support

### ISSUE THREAD

**Issue by Merith-TK** [packwiz/packwiz#100] opened 2022-04-01 19:53 UTC
potential implementatioN
`packwiz gh install <link to github release page>`

then it would check the API for the files on that release, add the jar if found, if multiple found display options, 
the api already has support for file hashes so less work lol

**Comment by wafflecoffee** [comment] 2022-04-01 19:53
duplicate #30

**Comment by comp500** [comment] 2022-05-03 20:39
Duplicate of #30

**Closed by comp500** 2022-05-03 20:39 UTC
