### ISSUE TITLE
[Suggestion] Make it so the user can specify if the mod is optional

### ISSUE THREAD

**Issue by Imzxhir** [packwiz/packwiz#209] opened 2023-04-12 22:37 UTC
Description: I would like a feature where the user can specify whether to make the mod optional when installing the mod. This can make it easier for some modpack developers or maybe just regular users who want to disable some mods on startup, this also makes the process of making a mod optional easier as the user would not have to go in each file and add an option to make it optional.

**Comment by comp500** [comment] 2023-04-12 22:47
Duplicate of https://github.com/packwiz/packwiz-installer/issues/6

**Closed by comp500** 2023-04-12 22:47 UTC

**Comment by DerRockWolf** [comment] 2024-12-31 16:53
I think this is not entirely a duplicate:

> this also makes the process of making a mod optional easier as the user would not have to go in each file and add an option to make it optional.

Currently the CLI doesn't support changing a mod to being optional, modpack developers need to manually adjust the pw.toml files to do so.
